import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f7fafd",
        "on-surface": "#181c1e",
        "inverse-surface": "#2d3133",
        tertiary: "#565554",
        "surface-container-highest": "#e0e3e6",
        "on-secondary-fixed": "#3a0a00",
        "surface-container-high": "#e5e8eb",
        "on-error-container": "#93000a",
        primary: "#0040e0",
        "surface-tint": "#124af0",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdbd0",
        "tertiary-fixed": "#e5e2e1",
        secondary: "#a73a15",
        "surface-variant": "#e0e3e6",
        "inverse-on-surface": "#eef1f4",
        "on-surface-variant": "#434656",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-primary-container": "#efefff",
        "secondary-fixed-dim": "#ffb59f",
        "on-primary-fixed": "#001356",
        "on-secondary-container": "#6a1b00",
        "surface-dim": "#d7dadd",
        "on-primary": "#ffffff",
        outline: "#747688",
        "primary-container": "#2e5bff",
        "surface-container-low": "#f1f4f7",
        "surface-bright": "#f7fafd",
        "error-container": "#ffdad6",
        "surface-container": "#ebeef1",
        "on-primary-fixed-variant": "#0035be",
        "on-secondary-fixed-variant": "#852400",
        "on-tertiary-fixed-variant": "#474646",
        "primary-fixed": "#dde1ff",
        "inverse-primary": "#b8c3ff",
        "outline-variant": "#c4c5d9",
        "on-background": "#181c1e",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-container": "#6e6d6d",
        "secondary-container": "#fe794f",
        "on-tertiary-container": "#f3f0ef",
        "primary-fixed-dim": "#b8c3ff",
        background: "#f7fafd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "container-max-width": "1280px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "display-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "label-md": [
          "14px",
          { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-xl": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
